[package]
name = "discord-link-sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.5"
eframe = "0.21.3"
tokio = "1.28.0"
