token = "MTEwMjcyMDU2OTIxODE4NzQyNg.G618M_.Ekys1xjNiIR8Lj-b9iAeHyOOg_NG6HirDQ8JmA"
channel_id = 1025817646433833023
invite_link = "https://discord.com/api/oauth2/authorize?client_id=1102720569218187426&permissions=277632769600&scope=bot"
bot_name = "Krankenwageninator"